// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int index = Integer.parseInt(args[0]);
		int biggerThanHalf = 0;
		int lessThanHalf = 0;
			for (int i=0; i<index; i++){
				double num = Math.random();
					if ( num > 0.5){
						biggerThanHalf++;
					}
					if ( num <= 0.5){
						lessThanHalf++;
					}
			}
				if (lessThanHalf == 0){
				System.out.println("> 0.5: " + biggerThanHalf);
				System.out.println("<= 0.5: " + lessThanHalf);
				}
				else {
				double ratio = (double) biggerThanHalf/lessThanHalf;
				System.out.println("> 0.5: " + biggerThanHalf);
				System.out.println("<= 0.5: " + lessThanHalf);
				System.out.println("Ratio " + ratio);
				}
	}
}
